const express = require("express");
const router = express.Router();
const { createPost, updatePost, deletePost, likePost, getPost, getTimeLinePosts } = require("../controllers/PostController");
router.route("/create").post(createPost);
router.route("/update/:id").put(updatePost);
router.route("/delete/:id").delete(deletePost);
router.route("/like/:id").put(likePost);
router.route("/:id").get(getPost);
router.route("/timelinePosts/:id").get(getTimeLinePosts);
module.exports = router;